services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    networks:
      - scraper-network
      
networks:
  scraper-network:
    driver: bridge