services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge